In [23]:
import pandas as pd
df = pd.read_csv('식당 평점 및 리뷰 수.csv')
df

         시도명  시군구        평점     방문자 리뷰 수    블로그 리뷰 수
0    강원특별자치도  강릉시  4.385164  1017.639344  262.049180
1    강원특별자치도  고성군  4.394643   559.571429  334.178571
2    강원특별자치도  동해시  4.363016   754.555556  182.142857
3    강원특별자치도  삼척시  4.280000   560.245614  128.736842
4    강원특별자치도  속초시  4.348367  1626.469388  790.836735
..       ...  ...       ...          ...         ...
223     충청북도  진천군  4.343409   532.522727   39.613636
224     충청북도  청주시  4.417287   891.251012   72.643725
225     충청북도  충주시  4.367285   468.152318   54.337748
226    서울특별시  도봉구  4.368846  1479.384615   52.384615
227    서울특별시  도봉구  4.368846  1479.384615   52.384615

[228 rows x 5 columns]

In [7]:
df_dobong = pd.read_csv('도봉구_혼밥식당.csv')
df_dobong['시도명'] = df_dobong['지역명'].apply(lambda x: x.split(' ')[0])
df_dobong['시군구'] = df_dobong['지역명'].apply(lambda x: x.split(' ')[1])

# 정보없음 떨구기
df_dobong = df_dobong[(df_dobong['평점'] != '정보 없음') & (df['방문자 리뷰 수'] != '정보 없음') & (df_dobong['블로그 리뷰 수'] != '정보 없음')].reset_index(drop=True)

# 문자형 -> 수치형 변수 전환
df_dobong['평점'] = df_dobong['평점'].apply(lambda x: x.replace('별점\n',''))
df_dobong['방문자 리뷰 수'] = df_dobong['방문자 리뷰 수'].apply(lambda x: x.replace('방문자 리뷰',''))
df_dobong['방문자 리뷰 수'] = df_dobong['방문자 리뷰 수'].apply(lambda x: x.replace(',',''))

df_dobong['블로그 리뷰 수'] = df_dobong['블로그 리뷰 수'].apply(lambda x: x.replace('블로그 리뷰',''))
df_dobong['블로그 리뷰 수'] = df_dobong['블로그 리뷰 수'].apply(lambda x: x.replace(',',''))

df_dobong['평점'] = df_dobong['평점'].astype('float64') 
df_dobong['방문자 리뷰 수'] = df_dobong['방문자 리뷰 수'].astype('int64') 
df_dobong['블로그 리뷰 수'] = df_dobong['블로그 리뷰 수'].astype('int64')

df_dobong

C:\Users\samsung-user\AppData\Local\Temp\ipykernel_13512\1133330672.py:6: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_dobong = df_dobong[(df_dobong['평점'] != '정보 없음') & (df['방문자 리뷰 수'] != '정보 없음') & (df_dobong['블로그 리뷰 수'] != '정보 없음')].reset_index(drop=True)

,지역명,가게 이름,카테고리,평점,방문자 리뷰 수,블로그 리뷰 수,주소,전화번호,시도명,시군구
0,서울특별시 도봉구 도봉동,김밥나라 도봉점,분식,4.27,3006,17,서울 도봉구 도봉로181길 6,02-956-8880,서울특별시,도봉구
1,서울특별시 도봉구 도봉동,카츠다담,돈가스,4.73,424,121,서울 도봉구 도봉로152길 31,0507-1447-6790,서울특별시,도봉구
2,서울특별시 도봉구 도봉동,청석골 멸치국수,국수,4.45,334,8,서울 도봉구 도봉로170길 34 원미빌딩 1층 3호,0507-1418-0708,서울특별시,도봉구
3,서울특별시 도봉구 도봉동,민들레김밥,김밥,4.25,755,17,서울 도봉구 마들로 686,02-956-7277,서울특별시,도봉구
4,서울특별시 도봉구 도봉동,함께밥상,종합분식,4.65,369,6,서울 도봉구 마들로 695,02-2088-6788,서울특별시,도봉구
5,서울특별시 도봉구 도봉동,비엣포 베트남쌀국수,베트남음식,4.36,955,60,서울 도봉구 마들로 676 1층,0507-1333-0574,서울특별시,도봉구
6,서울특별시 도봉구 도봉동,고향손칼국수 도봉,"칼국수,만두",4.37,976,24,서울 도봉구 도봉산4나길 6-5,02-956-7237,서울특별시,도봉구
7,서울특별시 도봉구 창동,수유리우동집 창동점,"우동,소바",4.47,3830,86,서울 도봉구 노해로65길 14 102호,0507-1386-5582,서울특별시,도봉구
8,서울특별시 도봉구 창동,잇팅엄마밥상 이마트창동점,"백반,가정식",4.42,694,11,서울 도봉구 노해로65길 4,정보 없음,서울특별시,도봉구
9,서울특별시 도봉구 창동,두레마을우동집,"우동,소바",4.27,1467,41,서울 도봉구 노해로69길 21-15,02-994-0010,서울특별시,도봉구
10,서울특별시 도봉구 창동,롯데리아 창동역점,햄버거,4.32,3248,43,서울 도봉구 노해로63길 78,02-900-2033,서울특별시,도봉구
11,서울특별시 도봉구 창동,김밥나라 창동점,분식,4.18,563,7,서울 도봉구 마들로11길 57,02-900-3855,서울특별시,도봉구
12,서울특별시 도봉구 창동,롯데리아 쌍문역점,햄버거,4.30,3017,34,서울 도봉구 도봉로 484,02-995-6263,서울특별시,도봉구
13,서울특별시 도봉구 창동,김밥타운 창동점,김밥,4.30,1107,14,서울 도봉구 도봉로110나길 31,02-902-6250,서울특별시,도봉구
14,서울특별시 도봉구 쌍문동,일심당,일본식라면,4.53,745,461,서울 도봉구 도봉로109길 24 1층 일심당,0507-1399-4155,서울특별시,도봉구
15,서울특별시 도봉구 쌍문동,수유리우동집 쌍문점,"우동,소바",4.37,2104,30,서울 도봉구 도봉로 581,02-994-5892,서울특별시,도봉구
16,서울특별시 도봉구 쌍문동,산책,일식당,4.35,1544,165,서울 도봉구 삼양로144길 18,02-997-6595,서울특별시,도봉구
17,서울특별시 도봉구 쌍문동,나드리김밥 한일병원점,분식,4.25,488,5,서울 도봉구 우이천로 308 한일병원 A동 1층,02-903-0300,서울특별시,도봉구
18,서울특별시 도봉구 쌍문동,KFC 우이동점,햄버거,4.32,4052,51,서울 도봉구 삼양로 544,02-995-1162,서울특별시,도봉구
19,서울특별시 도봉구 쌍문동,24시전주콩나물국밥 쌍문점,24시전주콩나물국밥,4.26,1017,18,서울 도봉구 도봉로 591,02-990-3777,서울특별시,도봉구
20,서울특별시 도봉구 방학동,얌샘김밥 방학역점,분식,4.24,1121,16,서울 도봉구 도봉로150길 43 135호,02-955-3378,서울특별시,도봉구
21,서울특별시 도봉구 방학동,틈새라면 방학점,분식,4.73,395,33,서울 도봉구 도봉로147길 5 1층,02-956-9333,서울특별시,도봉구
22,서울특별시 도봉구 방학동,김가네 방학역점,분식,4.24,1062,17,서울 도봉구 도봉로150길 43 1층 114호,02-955-2080,서울특별시,도봉구
23,서울특별시 도봉구 방학동,일심해장국 방학점,해장국,4.29,2474,50,서울 도봉구 방학로 204,02-956-7027,서울특별시,도봉구
24,서울특별시 도봉구 방학동,롯데리아 방학점,햄버거,4.29,2012,14,서울 도봉구 방학로 173,02-955-9538,서울특별시,도봉구
25,서울특별시 도봉구 방학동,봉구스밥버거 방학점,분식,4.38,705,13,서울 도봉구 도봉로150길 43 이에스에이아파트,02-3492-8476,서울특별시,도봉구

In [14]:
feat_df = df_dobong.groupby(['시도명','시군구'])[['평점','방문자 리뷰 수','블로그 리뷰 수']].mean().reset_index()
feat_df

     시도명  시군구        평점     방문자 리뷰 수   블로그 리뷰 수
0  서울특별시  도봉구  4.368846  1479.384615  52.384615

In [18]:
df = pd.concat([df,feat_df])

In [21]:
import pandas as pd
df_yj = pd.read_csv('연제구_혼밥식당.csv')

df_yj['시도명'] = df_yj['지역명'].apply(lambda x: x.split(' ')[0])
df_yj['시군구'] = df_yj['지역명'].apply(lambda x: x.split(' ')[1])

# 정보없음 떨구기
df_yj = df_yj[(df_yj['평점'] != '정보 없음') & (df_yj['방문자 리뷰 수'] != '정보 없음') & (df_yj['블로그 리뷰 수'] != '정보 없음')].reset_index(drop=True)

# 문자형 -> 수치형 변수 전환
df_yj['평점'] = df_yj['평점'].apply(lambda x: x.replace('별점\n',''))
df_yj['방문자 리뷰 수'] = df_yj['방문자 리뷰 수'].apply(lambda x: x.replace('방문자 리뷰',''))
df_yj['방문자 리뷰 수'] = df_yj['방문자 리뷰 수'].apply(lambda x: x.replace(',',''))

df_yj['블로그 리뷰 수'] = df_yj['블로그 리뷰 수'].apply(lambda x: x.replace('블로그 리뷰',''))
df_yj['블로그 리뷰 수'] = df_yj['블로그 리뷰 수'].apply(lambda x: x.replace(',',''))

df_yj['평점'] = df_yj['평점'].astype('float64') 
df_yj['방문자 리뷰 수'] = df_yj['방문자 리뷰 수'].astype('int64') 
df_yj['블로그 리뷰 수'] = df_yj['블로그 리뷰 수'].astype('int64')

df_yj

,지역명,가게 이름,카테고리,평점,방문자 리뷰 수,블로그 리뷰 수,주소,전화번호,시도명,시군구
0,부산광역시 연제구 연산동,김밥일번지 부산시청점,김밥,4.27,2393,54,부산 연제구 시청로 12,051-868-0322,부산광역시,연제구
1,부산광역시 연제구 연산동,롯데리아 부산연산점,햄버거,4.41,3184,31,부산 연제구 반송로 8,051-867-3166,부산광역시,연제구
2,부산광역시 연제구 연산동,미아리우동집 연산점,한식,4.64,483,36,부산 연제구 고분로 9 1층,0507-1429-9948,부산광역시,연제구
3,부산광역시 연제구 연산동,오니기리와이규동 부산연산역점,오니기리,4.34,341,41,부산 연제구 중앙대로 1110,051-853-0290,부산광역시,연제구
4,부산광역시 연제구 연산동,전주명물콩나물국밥,국밥,4.24,1093,58,부산 연제구 월드컵대로 153,051-852-3999,부산광역시,연제구
5,부산광역시 연제구 연산동,푸드카페 김밥천국 연산SK뷰점,분식,4.23,763,26,부산 연제구 중앙대로1124번길 15 연산동 에스케이 뷰,051-853-7999,부산광역시,연제구
6,부산광역시 연제구 연산동,샐러디 부산시청점,"다이어트,샐러드",4.51,537,60,부산 연제구 시청로 26-1 1층,051-865-0800,부산광역시,연제구
7,부산광역시 연제구 거제동,돗토리김밥 법조타운점,김밥,4.29,400,12,부산 연제구 법원남로15번길 12,051-503-5521,부산광역시,연제구
8,부산광역시 연제구 거제동,원초김밥,한식,4.50,925,24,부산 연제구 아시아드대로 82,051-503-9773,부산광역시,연제구
9,부산광역시 연제구 거제동,한솥도시락 사직학원가점,"도시락,컵밥",4.51,669,10,부산 연제구 아시아드대로 79 1층 102호,0507-1434-2925,부산광역시,연제구
10,부산광역시 연제구 거제동,홀썸,한식,4.23,1334,27,부산 연제구 법원남로9번길 17 2층 (동해선 거제역),051-715-8181,부산광역시,연제구
11,부산광역시 연제구 거제동,롯데리아 부산거제점,햄버거,4.51,1603,17,부산 연제구 아시아드대로 80,051-506-0134,부산광역시,연제구
12,부산광역시 연제구 거제동,고봉민김밥인 부산거제리점,분식,4.30,624,14,부산 연제구 아시아드대로 96 1층 고봉민김밥인 거제리점,0507-1464-1288,부산광역시,연제구
13,부산광역시 연제구 거제동,1호할매칼국수,"칼국수,만두",4.35,320,42,부산 연제구 거제시장로14번길 28 (주)거제시장,051-864-2410,부산광역시,연제구
14,부산광역시 연제구 거제동,써니김밥,김밥,4.50,426,5,부산 연제구 월드컵대로 266 거제동 롯데캐슬피렌체,051-503-1788,부산광역시,연제구
15,부산광역시 연제구 거제동,김밥일번지,김밥,4.40,614,20,부산 연제구 중앙대로 1206,0507-1444-6062,부산광역시,연제구

In [22]:
gb_df = df_yj.groupby(['시도명','시군구'])[['평점','방문자 리뷰 수','블로그 리뷰 수']].mean().reset_index()
gb_df

     시도명  시군구        평점  방문자 리뷰 수  블로그 리뷰 수
0  부산광역시  연제구  4.389375  981.8125   29.8125

In [24]:
df = pd.concat([df,gb_df])

In [25]:
df.to_csv('식당 평점 및 리뷰 수.csv',index=False)